<a href="https://colab.research.google.com/github/pritam17/MyProject1/blob/master/Deep_FFN_with_TF_2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x

In [0]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [0]:
x1=np.random.randint(1,30,200000)
x2=np.random.randint(1,30,200000)
x=pd.DataFrame({'x1':x1,'x2':x2})
y=4+2*x1+3*x2+3*np.random.random(200000)

In [0]:
x

x1  x2
0       16  20
1        5   4
2       29  27
3       17  15
4       27  18
...     ..  ..
199995  21   8
199996  10  16
199997  15  28
199998  19  11
199999  24  29

[200000 rows x 2 columns]

In [0]:
class preds:
    def __init__(self):
        self.w1=tf.Variable(0.0)
        self.w2=tf.Variable(0.0)
        self.b=tf.Variable(0.0)
    
    def __call__(self,x):
        result=self.w1*x.iloc[:,0]+self.w2*x.iloc[:,1]+self.b
        return(result)

In [0]:
model=preds()

In [0]:
model(x)

<tf.Tensor: shape=(200000,), dtype=float32, numpy=array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)>

In [0]:
model(x).numpy()

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [0]:
def loss(predicted_y, target_y):
    return tf.reduce_mean(tf.square(predicted_y - target_y))

In [0]:
def train(model, inputs, outputs, learning_rate):
    with tf.GradientTape() as t:
        current_loss = loss(model(inputs), outputs)
    dw1,dw2, db = t.gradient(current_loss, [model.w1,model.w2, model.b])
    model.w1.assign_sub(learning_rate * dw1)
    model.w2.assign_sub(learning_rate * dw2)
    model.b.assign_sub(learning_rate * db)

In [0]:
model = preds()

# Collect the history of W-values and b-values to plot later
w1s,w2s, bs = [], [],[]

epochs = range(500)
for epoch in epochs:
      for j in range(0,np.int(x.shape[0]/100),100):
        inputs=x.iloc[j:j+100,:]
        outputs=y[j:j+100]
        train(model, inputs, outputs, learning_rate=0.001)
      w1s.append(model.w1.numpy())
      w2s.append(model.w2.numpy())
      bs.append(model.b.numpy())
    
    # rand_ind=np.random.choice(range(x.shape[0]),100)
    # outputs=y[rand_ind]
    # inputs=x.iloc[rand_ind,:]
    
      current_loss = loss(model(inputs), outputs)

    
      print('Epoch %2d: W1=%1.2f W2=%1.2f b=%1.2f, loss=%2.5f' %
          (epoch, w1s[-1],w2s[-1], bs[-1], current_loss))

Epoch  0: W1=2.17 W2=3.12 b=0.19, loss=3.90081
Epoch  1: W1=2.15 W2=3.14 b=0.22, loss=3.93219
Epoch  2: W1=2.15 W2=3.14 b=0.25, loss=3.90050
Epoch  3: W1=2.15 W2=3.14 b=0.27, loss=3.86392
Epoch  4: W1=2.15 W2=3.14 b=0.30, loss=3.82750
Epoch  5: W1=2.15 W2=3.14 b=0.33, loss=3.79147
Epoch  6: W1=2.15 W2=3.14 b=0.36, loss=3.75584
Epoch  7: W1=2.15 W2=3.14 b=0.39, loss=3.72061
Epoch  8: W1=2.15 W2=3.14 b=0.42, loss=3.68578
Epoch  9: W1=2.15 W2=3.13 b=0.45, loss=3.65133
Epoch 10: W1=2.14 W2=3.13 b=0.47, loss=3.61726
Epoch 11: W1=2.14 W2=3.13 b=0.50, loss=3.58358
Epoch 12: W1=2.14 W2=3.13 b=0.53, loss=3.55027
Epoch 13: W1=2.14 W2=3.13 b=0.56, loss=3.51733
Epoch 14: W1=2.14 W2=3.13 b=0.58, loss=3.48477
Epoch 15: W1=2.14 W2=3.13 b=0.61, loss=3.45256
Epoch 16: W1=2.14 W2=3.13 b=0.64, loss=3.42071
Epoch 17: W1=2.14 W2=3.13 b=0.66, loss=3.38922
Epoch 18: W1=2.14 W2=3.13 b=0.69, loss=3.35808
Epoch 19: W1=2.14 W2=3.13 b=0.72, loss=3.32728
Epoch 20: W1=2.14 W2=3.13 b=0.74, loss=3.29684
Epoch 21: W1=

## **Binary Classification With Tensorflow**

In [0]:
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
import numpy as np
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import roc_auc_score

In [0]:
!wget https://www.dropbox.com/s/v7fq3tage2au7s0/Subscribers.csv -P 'drive/My Drive/Colab Notebooks/'

--2019-12-21 09:46:14--  https://www.dropbox.com/s/v7fq3tage2au7s0/Subscribers.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.9.1, 2620:100:601f:1::a27d:901
Connecting to www.dropbox.com (www.dropbox.com)|162.125.9.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/v7fq3tage2au7s0/Subscribers.csv [following]
--2019-12-21 09:46:14--  https://www.dropbox.com/s/raw/v7fq3tage2au7s0/Subscribers.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucced14a27fc197428cc442a870f.dl.dropboxusercontent.com/cd/0/inline/AupV8BLrDrXRrzKaFTr3mN24flGFl6IWysmXLdPH3_zX18rRPXOMOm6nu9L-SSJCQLuOSxJ89_yVxXxrKtRkuKynyA_uN5xbYghK2DIKwEbbEg/file# [following]
--2019-12-21 09:46:15--  https://ucced14a27fc197428cc442a870f.dl.dropboxusercontent.com/cd/0/inline/AupV8BLrDrXRrzKaFTr3mN24flGFl6IWysmXLdPH3_zX18rRPXOMOm6nu9L-SSJCQLuOSxJ89_yVxXxrKtRkuKynyA_uN5xbYghK2DIKwEbbEg/file
Resolving 

In [0]:
data=pd.read_csv("drive/My Drive/Colab Notebooks/Subscribers.csv")

In [0]:
data.shape

(300000, 51)

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
data.head()

V1           V2          V3  ...   V49       V50  Subscribers
0 -0.211875    743952.92   743952.92  ...  28.0   2557.22            0
1  0.241488  11295310.87  8034290.99  ...  19.0  12807.07            0
2  0.459032     20363.68   317922.94  ...   0.0     32.12            1
3  0.000000    856120.91   856120.91  ...  19.0   2029.79            0
4  8.270783    194485.64   412330.33  ...   0.0     26.95            0

[5 rows x 51 columns]

In [0]:
y=pd.get_dummies(data['Subscribers'])

In [0]:
y

0  1
0       1  0
1       1  0
2       0  1
3       1  0
4       1  0
...    .. ..
299995  1  0
299996  1  0
299997  1  0
299998  1  0
299999  0  1

[300000 rows x 2 columns]

In [0]:
x=data.drop(['Subscribers'],axis=1)

In [0]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,
                                               random_state=2)

In [0]:
x_train

V1         V2         V3  ...           V48    V49       V50
18736  -0.629091  228317.55  117202.89  ...    663.866667   10.0     98.30
147527  0.000000  179586.61  179586.61  ...    449.400000   19.0    449.40
1729   -0.108635  107500.00  106724.14  ...   1327.910000   32.0   1254.93
189132  0.344743  581827.88  581810.16  ...   1044.460000    0.0   1040.95
280431  0.531380  250918.54  149340.88  ...    963.563333    0.0    178.50
...          ...        ...        ...  ...           ...    ...       ...
33867   0.013980  190788.69  282149.59  ...   1373.640000   53.0    942.90
84434   0.036289  153162.20  142944.78  ...    704.186667    0.0    206.02
95816  -0.469078  566118.15   76905.23  ...  23254.696670    7.0  22931.90
203245  0.036412  286019.00  282964.79  ...    641.680000  129.0    546.92
100879  0.035484  329115.32  329115.32  ...    804.676667  342.0    866.38

[240000 rows x 50 columns]

In [0]:
x_train.reset_index(drop=True,inplace=True)
y_train.reset_index(drop=True,inplace=True)

In [0]:
st=StandardScaler()

In [0]:
st.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [0]:
x_train=pd.DataFrame(st.transform(x_train))
x_test=pd.DataFrame(st.transform(x_test))

In [0]:
x_train.shape

(240000, 50)

# simple logistic regression

In [0]:
weights = tf.Variable(tf.random.normal(shape=(50, 2), dtype=tf.float64))
biases  = tf.Variable(tf.random.normal(shape=(2,), dtype=tf.float64))

In [0]:
def logistic_regression(x):
    lr = tf.add(tf.matmul(x, weights), biases)
    return lr


def cross_entropy(y_true, y_pred):
    loss = tf.nn.softmax_cross_entropy_with_logits(labels=y_true, logits=y_pred)
    return tf.reduce_mean(loss)

def accuracy(y_true, y_pred):
    y_true = tf.cast(tf.argmax(y_true, axis=1), dtype=tf.int32)
    preds = tf.cast(tf.argmax(y_pred, axis=1), dtype=tf.int32)
    preds = tf.equal(y_true, preds)
    return tf.reduce_mean(tf.cast(preds, dtype=tf.float32))

def roc_auc(y_true,x):
    y_true = tf.cast(tf.argmax(y_true, axis=1), dtype=tf.int32).numpy()
    y_pred=tf.nn.softmax(logistic_regression(x))[:,1]
    return(roc_auc_score(y_true,y_pred))

def grad(x, y):
    with tf.GradientTape() as tape:
        y_pred = logistic_regression(x)
        loss_val = cross_entropy(y, y_pred)
    return tape.gradient(loss_val, [weights, biases]),loss_val

In [0]:
epochs=2000

In [0]:
learning_rate=0.01
loss_list=[]
for epoch in range(epochs):
  
    #rand_ind=np.random.choice(range(x_train.shape[0]),100)
    #outputs=y_train.iloc[rand_ind,:].values
    #inputs=x_train.iloc[rand_ind,:].values

  for j in range(0,np.int(x_train.shape[0]/100),100):
    outputs=y_train.iloc[j:j+100,:].values
    inputs=x_train.iloc[j:j+100].values
    
    wts,loss=grad(inputs,tf.cast(outputs,'float32'))
    
    weights.assign_sub(learning_rate*wts[0])
    biases.assign_sub(learning_rate*wts[1])
  loss_list.append(loss.numpy())
  if epoch%50==0:
    print(accuracy(y_test.values,logistic_regression(x_test.values)).numpy(),roc_auc(y_test.values,x_test.values))
    
    

0.7668167 0.6276370960006901
0.8124 0.6312980315095917
0.8174 0.6422347163848918
0.81965 0.6477188252511283
0.82095 0.6519828707353742
0.82265 0.6559096780806616
0.82376665 0.6597513352820331
0.8246833 0.663492459338098
0.8251167 0.6670485858779112
0.8254167 0.6703669699726549
0.82575 0.6733810213084395
0.8262333 0.6761831482815674
0.8268167 0.6787328121359761
0.82708335 0.6811670502397434
0.82733333 0.6835251206532553
0.8277 0.6857875052227179
0.82806665 0.6879837234461965
0.8284 0.6901353683803204
0.8287 0.6921898172068432
0.82883334 0.6941452802732251
0.82895 0.6960538177121975
0.82915 0.6978228296580813
0.8293167 0.6994573255749734
0.82946664 0.7009715923997724
0.8296667 0.7023795683215839
0.8297833 0.703652577870615
0.8298333 0.7048739805613569
0.82981664 0.7060279801702435
0.82986665 0.7070918826917303
0.82996666 0.70805712280187
0.8301333 0.7089957525762067
0.8302 0.709909198266219
0.83021665 0.7107891290002574
0.8302 0.7116323581808406
0.83026665 0.7124315748038148
0.83035 0.71

In [0]:
len(loss_list)

2000

In [0]:
wts=grad(inputs,tf.cast(outputs,'float32'))

In [0]:
wts[0][1]

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([-0.04448503,  0.04448503])>

# classfier with a hidden layer

In [0]:
db

NameError: ignored

In [0]:
weights_h = tf.Variable(tf.random.truncated_normal(shape=(50, 20), dtype=tf.float64))
biases_h  = tf.Variable(tf.random.truncated_normal(shape=(20,), dtype=tf.float64))

weights_o = tf.Variable(tf.random.truncated_normal(shape=(20, 2), dtype=tf.float64))
biases_o  = tf.Variable(tf.random.truncated_normal(shape=(2,), dtype=tf.float64))

In [0]:
def logistic_regression(x):
    h_o = tf.add(tf.matmul(x, weights_h), biases_h)
    h_o=tf.nn.relu(h_o)
    lr=tf.add(tf.matmul(h_o, weights_o), biases_o)
    return lr


def cross_entropy(y_true, y_pred):

    loss = tf.nn.softmax_cross_entropy_with_logits(labels=y_true, logits=y_pred)
    return tf.reduce_mean(loss)


def accuracy(y_true, y_pred):
    y_true = tf.cast(tf.argmax(y_true, axis=1), dtype=tf.int32)
    preds = tf.cast(tf.argmax(y_pred, axis=1), dtype=tf.int32)
    preds = tf.equal(y_true, preds)
    return tf.reduce_mean(tf.cast(preds, dtype=tf.float32))

def roc_auc(y_true,x):
    y_true = tf.cast(tf.argmax(y_true, axis=1), dtype=tf.int32).numpy()
    y_pred=tf.nn.softmax(logistic_regression(x))[:,1]
    return(roc_auc_score(y_true,y_pred))

def grad(x, y):
    with tf.GradientTape() as tape:
        y_pred = logistic_regression(x)
        loss_val = cross_entropy(y, y_pred)
    return tape.gradient(loss_val, [weights_h, biases_h,weights_o, biases_o])

In [0]:
epochs=2000

In [0]:
learning_rate=0.01
for epoch in range(epochs):
    #rand_ind=np.random.choice(range(x_train.shape[0]),100)
    #outputs=y_train.iloc[rand_ind,:].values
    #inputs=x_train.iloc[rand_ind,:].values
    for j in range(0,np.int(x_train.shape[0]/100),100):
      outputs=y_train.iloc[j:j+100,:].values
      inputs=x_train.iloc[j:j+100].values
    
      dw_h,db_h,dw_o,db_o=grad(inputs,tf.cast(outputs,'float32'))
    
      weights_h.assign_sub(learning_rate*dw_h)
      biases_h.assign_sub(learning_rate*db_h)
      weights_o.assign_sub(learning_rate*dw_o)
      biases_o.assign_sub(learning_rate*db_o)
    
    if epoch%50==0:
        print(accuracy(y_test.values,logistic_regression(x_test.values)).numpy(),roc_auc(y_test.values,x_test.values))
    
    

0.70678335 0.5236426474090884
0.81666666 0.5812160617110959
0.82448334 0.617173537816167
0.82706666 0.6400648076167675
0.82781667 0.6528712056074051
0.8284 0.6603768774578562
0.8283333 0.6659013922238535
0.82858336 0.6705259989662685
0.82876664 0.674607268369785
0.8290667 0.6782006308189156
0.82918334 0.6814528514983288
0.82923335 0.6844973865172532
0.82948333 0.6872240667409417
0.82948333 0.6897981966695129
0.82953334 0.692128435641504
0.8298333 0.6943590636472263
0.83033335 0.6965086747076668
0.8305167 0.6986112116542422
0.83096665 0.7006845690585847
0.8308833 0.7025755186676821
0.8312 0.7044123840392098
0.8311667 0.7062623416178018
0.83131665 0.7081042174303107
0.83166665 0.7098055302983135
0.8318167 0.7115902808315732
0.83195 0.7133802362058447
0.83206666 0.715086701163092
0.8324 0.7167064480766819
0.83243334 0.7183778057560993
0.83273333 0.719934509423689
0.8333167 0.7214643008981422
0.83353335 0.7228720013385038
0.83393335 0.7240514722357798
0.83426666 0.7249951954862869
0.83425 

In [0]:
%tensorflow_version

Currently selected TF version: 1.x
Available versions:
* 1.x
* 2.x
